# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from flexiv_crtk/RobotStates.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class RobotStates(genpy.Message):
  _md5sum = "9ca6fd6ae4c4a0b14dbb192201e94af1"
  _type = "flexiv_crtk/RobotStates"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64[7] measured_jp
geometry_msgs/Pose measrued_cp
geometry_msgs/Pose goal_cp
geometry_msgs/Twist measured_cv
geometry_msgs/Wrench measured_cf

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Wrench
# This represents force in free space, separated into
# its linear and angular parts.
Vector3  force
Vector3  torque
"""
  __slots__ = ['measured_jp','measrued_cp','goal_cp','measured_cv','measured_cf']
  _slot_types = ['float64[7]','geometry_msgs/Pose','geometry_msgs/Pose','geometry_msgs/Twist','geometry_msgs/Wrench']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       measured_jp,measrued_cp,goal_cp,measured_cv,measured_cf

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotStates, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.measured_jp is None:
        self.measured_jp = [0.] * 7
      if self.measrued_cp is None:
        self.measrued_cp = geometry_msgs.msg.Pose()
      if self.goal_cp is None:
        self.goal_cp = geometry_msgs.msg.Pose()
      if self.measured_cv is None:
        self.measured_cv = geometry_msgs.msg.Twist()
      if self.measured_cf is None:
        self.measured_cf = geometry_msgs.msg.Wrench()
    else:
      self.measured_jp = [0.] * 7
      self.measrued_cp = geometry_msgs.msg.Pose()
      self.goal_cp = geometry_msgs.msg.Pose()
      self.measured_cv = geometry_msgs.msg.Twist()
      self.measured_cf = geometry_msgs.msg.Wrench()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_7d().pack(*self.measured_jp))
      _x = self
      buff.write(_get_struct_26d().pack(_x.measrued_cp.position.x, _x.measrued_cp.position.y, _x.measrued_cp.position.z, _x.measrued_cp.orientation.x, _x.measrued_cp.orientation.y, _x.measrued_cp.orientation.z, _x.measrued_cp.orientation.w, _x.goal_cp.position.x, _x.goal_cp.position.y, _x.goal_cp.position.z, _x.goal_cp.orientation.x, _x.goal_cp.orientation.y, _x.goal_cp.orientation.z, _x.goal_cp.orientation.w, _x.measured_cv.linear.x, _x.measured_cv.linear.y, _x.measured_cv.linear.z, _x.measured_cv.angular.x, _x.measured_cv.angular.y, _x.measured_cv.angular.z, _x.measured_cf.force.x, _x.measured_cf.force.y, _x.measured_cf.force.z, _x.measured_cf.torque.x, _x.measured_cf.torque.y, _x.measured_cf.torque.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.measrued_cp is None:
        self.measrued_cp = geometry_msgs.msg.Pose()
      if self.goal_cp is None:
        self.goal_cp = geometry_msgs.msg.Pose()
      if self.measured_cv is None:
        self.measured_cv = geometry_msgs.msg.Twist()
      if self.measured_cf is None:
        self.measured_cf = geometry_msgs.msg.Wrench()
      end = 0
      start = end
      end += 56
      self.measured_jp = _get_struct_7d().unpack(str[start:end])
      _x = self
      start = end
      end += 208
      (_x.measrued_cp.position.x, _x.measrued_cp.position.y, _x.measrued_cp.position.z, _x.measrued_cp.orientation.x, _x.measrued_cp.orientation.y, _x.measrued_cp.orientation.z, _x.measrued_cp.orientation.w, _x.goal_cp.position.x, _x.goal_cp.position.y, _x.goal_cp.position.z, _x.goal_cp.orientation.x, _x.goal_cp.orientation.y, _x.goal_cp.orientation.z, _x.goal_cp.orientation.w, _x.measured_cv.linear.x, _x.measured_cv.linear.y, _x.measured_cv.linear.z, _x.measured_cv.angular.x, _x.measured_cv.angular.y, _x.measured_cv.angular.z, _x.measured_cf.force.x, _x.measured_cf.force.y, _x.measured_cf.force.z, _x.measured_cf.torque.x, _x.measured_cf.torque.y, _x.measured_cf.torque.z,) = _get_struct_26d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.measured_jp.tostring())
      _x = self
      buff.write(_get_struct_26d().pack(_x.measrued_cp.position.x, _x.measrued_cp.position.y, _x.measrued_cp.position.z, _x.measrued_cp.orientation.x, _x.measrued_cp.orientation.y, _x.measrued_cp.orientation.z, _x.measrued_cp.orientation.w, _x.goal_cp.position.x, _x.goal_cp.position.y, _x.goal_cp.position.z, _x.goal_cp.orientation.x, _x.goal_cp.orientation.y, _x.goal_cp.orientation.z, _x.goal_cp.orientation.w, _x.measured_cv.linear.x, _x.measured_cv.linear.y, _x.measured_cv.linear.z, _x.measured_cv.angular.x, _x.measured_cv.angular.y, _x.measured_cv.angular.z, _x.measured_cf.force.x, _x.measured_cf.force.y, _x.measured_cf.force.z, _x.measured_cf.torque.x, _x.measured_cf.torque.y, _x.measured_cf.torque.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.measrued_cp is None:
        self.measrued_cp = geometry_msgs.msg.Pose()
      if self.goal_cp is None:
        self.goal_cp = geometry_msgs.msg.Pose()
      if self.measured_cv is None:
        self.measured_cv = geometry_msgs.msg.Twist()
      if self.measured_cf is None:
        self.measured_cf = geometry_msgs.msg.Wrench()
      end = 0
      start = end
      end += 56
      self.measured_jp = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=7)
      _x = self
      start = end
      end += 208
      (_x.measrued_cp.position.x, _x.measrued_cp.position.y, _x.measrued_cp.position.z, _x.measrued_cp.orientation.x, _x.measrued_cp.orientation.y, _x.measrued_cp.orientation.z, _x.measrued_cp.orientation.w, _x.goal_cp.position.x, _x.goal_cp.position.y, _x.goal_cp.position.z, _x.goal_cp.orientation.x, _x.goal_cp.orientation.y, _x.goal_cp.orientation.z, _x.goal_cp.orientation.w, _x.measured_cv.linear.x, _x.measured_cv.linear.y, _x.measured_cv.linear.z, _x.measured_cv.angular.x, _x.measured_cv.angular.y, _x.measured_cv.angular.z, _x.measured_cf.force.x, _x.measured_cf.force.y, _x.measured_cf.force.z, _x.measured_cf.torque.x, _x.measured_cf.torque.y, _x.measured_cf.torque.z,) = _get_struct_26d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_26d = None
def _get_struct_26d():
    global _struct_26d
    if _struct_26d is None:
        _struct_26d = struct.Struct("<26d")
    return _struct_26d
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
