# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from flexiv_crtk/RobotStates_CRTK.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class RobotStates_CRTK(genpy.Message):
  _md5sum = "57c0e118106470de81cca4c527be64f9"
  _type = "flexiv_crtk/RobotStates_CRTK"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
float64[7] measured_jp
geometry_msgs/Pose measured_cp
geometry_msgs/Pose goal_cp
geometry_msgs/Twist measured_cv
geometry_msgs/Wrench measured_cf

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Wrench
# This represents force in free space, separated into
# its linear and angular parts.
Vector3  force
Vector3  torque
"""
  __slots__ = ['header','measured_jp','measured_cp','goal_cp','measured_cv','measured_cf']
  _slot_types = ['std_msgs/Header','float64[7]','geometry_msgs/Pose','geometry_msgs/Pose','geometry_msgs/Twist','geometry_msgs/Wrench']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,measured_jp,measured_cp,goal_cp,measured_cv,measured_cf

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotStates_CRTK, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.measured_jp is None:
        self.measured_jp = [0.] * 7
      if self.measured_cp is None:
        self.measured_cp = geometry_msgs.msg.Pose()
      if self.goal_cp is None:
        self.goal_cp = geometry_msgs.msg.Pose()
      if self.measured_cv is None:
        self.measured_cv = geometry_msgs.msg.Twist()
      if self.measured_cf is None:
        self.measured_cf = geometry_msgs.msg.Wrench()
    else:
      self.header = std_msgs.msg.Header()
      self.measured_jp = [0.] * 7
      self.measured_cp = geometry_msgs.msg.Pose()
      self.goal_cp = geometry_msgs.msg.Pose()
      self.measured_cv = geometry_msgs.msg.Twist()
      self.measured_cf = geometry_msgs.msg.Wrench()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(_get_struct_7d().pack(*self.measured_jp))
      _x = self
      buff.write(_get_struct_26d().pack(_x.measured_cp.position.x, _x.measured_cp.position.y, _x.measured_cp.position.z, _x.measured_cp.orientation.x, _x.measured_cp.orientation.y, _x.measured_cp.orientation.z, _x.measured_cp.orientation.w, _x.goal_cp.position.x, _x.goal_cp.position.y, _x.goal_cp.position.z, _x.goal_cp.orientation.x, _x.goal_cp.orientation.y, _x.goal_cp.orientation.z, _x.goal_cp.orientation.w, _x.measured_cv.linear.x, _x.measured_cv.linear.y, _x.measured_cv.linear.z, _x.measured_cv.angular.x, _x.measured_cv.angular.y, _x.measured_cv.angular.z, _x.measured_cf.force.x, _x.measured_cf.force.y, _x.measured_cf.force.z, _x.measured_cf.torque.x, _x.measured_cf.torque.y, _x.measured_cf.torque.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.measured_cp is None:
        self.measured_cp = geometry_msgs.msg.Pose()
      if self.goal_cp is None:
        self.goal_cp = geometry_msgs.msg.Pose()
      if self.measured_cv is None:
        self.measured_cv = geometry_msgs.msg.Twist()
      if self.measured_cf is None:
        self.measured_cf = geometry_msgs.msg.Wrench()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 56
      self.measured_jp = _get_struct_7d().unpack(str[start:end])
      _x = self
      start = end
      end += 208
      (_x.measured_cp.position.x, _x.measured_cp.position.y, _x.measured_cp.position.z, _x.measured_cp.orientation.x, _x.measured_cp.orientation.y, _x.measured_cp.orientation.z, _x.measured_cp.orientation.w, _x.goal_cp.position.x, _x.goal_cp.position.y, _x.goal_cp.position.z, _x.goal_cp.orientation.x, _x.goal_cp.orientation.y, _x.goal_cp.orientation.z, _x.goal_cp.orientation.w, _x.measured_cv.linear.x, _x.measured_cv.linear.y, _x.measured_cv.linear.z, _x.measured_cv.angular.x, _x.measured_cv.angular.y, _x.measured_cv.angular.z, _x.measured_cf.force.x, _x.measured_cf.force.y, _x.measured_cf.force.z, _x.measured_cf.torque.x, _x.measured_cf.torque.y, _x.measured_cf.torque.z,) = _get_struct_26d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(self.measured_jp.tostring())
      _x = self
      buff.write(_get_struct_26d().pack(_x.measured_cp.position.x, _x.measured_cp.position.y, _x.measured_cp.position.z, _x.measured_cp.orientation.x, _x.measured_cp.orientation.y, _x.measured_cp.orientation.z, _x.measured_cp.orientation.w, _x.goal_cp.position.x, _x.goal_cp.position.y, _x.goal_cp.position.z, _x.goal_cp.orientation.x, _x.goal_cp.orientation.y, _x.goal_cp.orientation.z, _x.goal_cp.orientation.w, _x.measured_cv.linear.x, _x.measured_cv.linear.y, _x.measured_cv.linear.z, _x.measured_cv.angular.x, _x.measured_cv.angular.y, _x.measured_cv.angular.z, _x.measured_cf.force.x, _x.measured_cf.force.y, _x.measured_cf.force.z, _x.measured_cf.torque.x, _x.measured_cf.torque.y, _x.measured_cf.torque.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.measured_cp is None:
        self.measured_cp = geometry_msgs.msg.Pose()
      if self.goal_cp is None:
        self.goal_cp = geometry_msgs.msg.Pose()
      if self.measured_cv is None:
        self.measured_cv = geometry_msgs.msg.Twist()
      if self.measured_cf is None:
        self.measured_cf = geometry_msgs.msg.Wrench()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 56
      self.measured_jp = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=7)
      _x = self
      start = end
      end += 208
      (_x.measured_cp.position.x, _x.measured_cp.position.y, _x.measured_cp.position.z, _x.measured_cp.orientation.x, _x.measured_cp.orientation.y, _x.measured_cp.orientation.z, _x.measured_cp.orientation.w, _x.goal_cp.position.x, _x.goal_cp.position.y, _x.goal_cp.position.z, _x.goal_cp.orientation.x, _x.goal_cp.orientation.y, _x.goal_cp.orientation.z, _x.goal_cp.orientation.w, _x.measured_cv.linear.x, _x.measured_cv.linear.y, _x.measured_cv.linear.z, _x.measured_cv.angular.x, _x.measured_cv.angular.y, _x.measured_cv.angular.z, _x.measured_cf.force.x, _x.measured_cf.force.y, _x.measured_cf.force.z, _x.measured_cf.torque.x, _x.measured_cf.torque.y, _x.measured_cf.torque.z,) = _get_struct_26d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_26d = None
def _get_struct_26d():
    global _struct_26d
    if _struct_26d is None:
        _struct_26d = struct.Struct("<26d")
    return _struct_26d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
